// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ejoeqakgkonqhujwiaaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqb2VxYWtna29ucWh1andpYWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NzY5NTYsImV4cCI6MjA3OTU1Mjk1Nn0.B-ZVht-vNaRz3Y8ufyBHZLWo1L_aW_c63q2shAxHd7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);